# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя точки')),
                ('code', models.CharField(max_length=20, verbose_name='Код точки')),
                ('address', models.CharField(max_length=20, verbose_name='Адрес точки')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя типа точки')),
                ('description', models.CharField(max_length=20, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PointType'),
        ),
    ]
